name: 'Test 2'

on: push

jobs:
  test:
    name: "Test code and check lint"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: "os-independent pip cache dir"
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: "cache python dependencies"
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: python -m pip install --upgrade pip -e .[dev]

      - name: "`make lint test`"
        run: make lint test


##  notify-workflow-complete:
##    name: notify
##    needs: [release-jobbergate-cli-snap-to-edge]
##    runs-on: "ubuntu-latest"
##    steps:
##      - uses: 8398a7/action-slack@v3
##        if: always()
##        with:
##          status: ${{ job.status }}
##          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
##        env:
##          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
##
